apiVersion: apps/v1
kind: Deployment
metadata:
  name: dokdok-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dokdok-server
  template:
    metadata:
      labels:
        run: dokdok-server
    spec:
      containers:
      - image: alinos/dokdok-server:1.0
        name: dokdok-server
        imagePullPolicy: Always
        ports:
        - containerPort: 4000