apiVersion: v1
kind: Deployment
metadata:
  name: dokdok-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dokdok-server
  template:
    metadata:
      labels:
        run: dokdok-server
    spec:
      containers:
      - image: dokdok-server
        name: dokdok-server
        ports:
        - containerPort: 4000